name: .NET WebApp Auto Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish -c Release -o publish

      - name: Upload full publish to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "publish/**"
          target: "/home/ubuntu/myapp/"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            mkdir -p /home/ubuntu/myapp/publish
            mkdir -p /home/ubuntu/.dotnet

            sudo pkill -f MyWebHtmlApp.dll || true

            sudo chown -R ubuntu:ubuntu /home/ubuntu/myapp
            sudo chown -R ubuntu:ubuntu /home/ubuntu/.dotnet
            sudo chmod -R 755 /home/ubuntu/myapp

            sudo tee /etc/systemd/system/mywebapp.service > /dev/null << 'EOF'
            [Unit]
            Description=My .NET WebApp
            After=network.target

            [Service]
            WorkingDirectory=/home/ubuntu/myapp/publish
            ExecStart=/usr/bin/dotnet /home/ubuntu/myapp/publish/MyWebHtmlApp.dll
            Restart=always
            RestartSec=10
            SyslogIdentifier=mywebapp
            User=ubuntu
            Environment=ASPNETCORE_ENVIRONMENT=Production
            Environment=DOTNET_CLI_HOME=/home/ubuntu

            [Install]
            WantedBy=multi-user.target
            EOF

            sudo systemctl daemon-reload
            sudo systemctl enable mywebapp
            sudo systemctl restart mywebapp

            sudo rm -rf /var/www/html/*
            sudo cp -r /home/ubuntu/myapp/publish/wwwroot/* /var/www/html/
            sudo chown -R www-data:www-data /var/www/html
            sudo chmod -R 755 /var/www/html
            sudo systemctl reload nginx